eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
logging:
  level:
    io:
      seata: debug
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: cn.codemao.codemaster.order.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8184
spring:
  application:
    name: order
  datasource:
    hikari:
      connection-test-query: select 1
      maximum-pool-size: 30
      minimum-idle: 10
      read-only: false
      connection-timeout: 30000
      validation-timeout: 3000
      max-lifetime: 30000
      login-timeout: 5
      idle-timeout: 30000
  flyway:
    enabled: true

